# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

ModuleNotFoundError: No module named 'generators'

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
np.show_config()

1.21.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512C

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [6]:
memory_size = vector.nbytes
print(memory_size)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
python -c "import numpy; numpy.info(numpy.add)"

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
vector = np.zeros(10)
vector[4] = 1
print(vector, vector[4])

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] 1.0


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [11]:
vector = vector[::-1]
print(vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
print(np.arange(9).reshape(3, 3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [19]:
non_zero = np.nonzero([1,2,0,0,4,0])
print(non_zero)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [20]:
mtx = np.eye(3)
print(mtx)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [21]:
array = np.random.random((3,3,3))
print(array)

[[[0.75081011 0.549457   0.48751095]
  [0.46178653 0.95553089 0.99900765]
  [0.26803403 0.74527959 0.5307141 ]]

 [[0.52417987 0.17281479 0.69945624]
  [0.61139699 0.46583339 0.21854243]
  [0.9733564  0.52465286 0.49735567]]

 [[0.56507981 0.21670499 0.17748794]
  [0.38306016 0.92725857 0.22910064]
  [0.17537724 0.50481343 0.46583674]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [22]:
array = np.random.random((10, 10))
array_min, array_max = array.min(), array.max()
print(array_min, array_max)


0.0015997124573571275 0.9911881024579162


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [23]:
vector = np.random.random(30)
print(vector.mean())

0.3904446300906542


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [24]:
array = np.zeros((10, 10))
array[0:, 0] = 1
array[0, 0:] = 1
array[0:, -1] = 1
array[-1, 0:] = 1
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [32]:
array = np.ones((5,5))
array = np.pad(array, pad_width = 1, mode = 'constant', constant_values = 0)
print(array)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [34]:
print(0 * np.nan,
np.nan == np.nan,
np.inf > np.nan,
np.nan - np.nan,
np.nan in set([np.nan]),
0.3 == 3 * 0.1)

nan False False nan True False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [35]:
mtx = np.diag(1 + np.arange(4),k = -1)
print(mtx)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [36]:
mtx = np.zeros((8, 8))
mtx[1::2, ::2] = 1
mtx[::2, 1::2] = 1
print(mtx)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [37]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [41]:
mtx = np.array([[1, 0], [0, 1]])
checkerboard = np.tile(mtx, (4, 4))
print(checkerboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [44]:
mtx = np.random.random((5, 5))
mtx_max, mtx_min = mtx.max(), mtx.min()
mtx = (mtx - mtx_min) / (mtx_max - mtx_min)
print(mtx)

[[0.21851539 1.         0.53682381 0.13561641 0.11088448]
 [0.43777562 0.7266709  0.58763127 0.96148182 0.27398651]
 [0.86782516 0.46217735 0.96509473 0.40270063 0.79169223]
 [0.         0.24538364 0.47444611 0.89479021 0.52171009]
 [0.03393689 0.95462378 0.0602008  0.87634721 0.86155076]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [45]:
dtype_rgba = np.dtype([
    ('r', np.uint8),
    ('g', np.uint8),
    ('b', np.uint8),
    ('a', np.uint8)
])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [46]:
mtx = np.dot(np.ones((5, 3)), np.ones((3, 2)))
print(mtx)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [47]:
mtx = np.random.random(10)
mtx[4:8] = -mtx[4:8]
print(mtx)

[ 0.23681545  0.59444572  0.6175739   0.95443847 -0.73769813 -0.43129567
 -0.81869653 -0.02242233  0.34764902  0.84490432]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [48]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [52]:
Z = np.arange(10, 15)
print(Z**Z,
2 << Z >> 2,
Z <- Z,
1j*Z,
Z/1/1)
print("Z<Z>Z not legal")

[ 1410065408  1843829075  -251658240 -1692154371 -1282129920] [ 512 1024 2048 4096 8192] [False False False False False] [0.+10.j 0.+11.j 0.+12.j 0.+13.j 0.+14.j] [10. 11. 12. 13. 14.]
Z<Z>Z not legal


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [53]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\kvakv\AppData\Local\Temp\ipykernel_7136\3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\kvakv\AppData\Local\Temp\ipykernel_7136\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [54]:
array = np.array([5.4, 3.2, -1.2, 0.0, -10.1])
array = np.copysign(np.ceil(np.abs(array)), array)
print(array)

[  6.   4.  -2.   0. -11.]


#### 30. How to find common values between two arrays? (★☆☆)

In [55]:
x = np.random.randint(0, 10, 10)
y = np.random.randint(0, 10, 10)
print(np.intersect1d(x, y))

[1 2 3 4 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [56]:
np.seterr(all='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [57]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [58]:
today = np.datetime64('today', 'D')

yesterday = today - np.timedelta64(1, 'D')

tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday's date:", yesterday)
print("Today's date:", today)
print("Tomorrow's date:", tomorrow)

Yesterday's date: 2023-03-30
Today's date: 2023-03-31
Tomorrow's date: 2023-04-01


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [59]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [60]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [61]:
x = np.random.randint(0, 10, 10)

print(x // 1)
print(np.floor(x))
print(np.trunc(x))
print(x.astype(int))

[4 8 1 0 3 2 0 5 6 3]
[4. 8. 1. 0. 3. 2. 0. 5. 6. 3.]
[4. 8. 1. 0. 3. 2. 0. 5. 6. 3.]
[4 8 1 0 3 2 0 5 6 3]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [62]:
x = np.zeros((5, 5), dtype=int)
x += np.arange(5)
print(x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [63]:
def my_generator():
    for i in range(10):
        yield i
a = np.fromiter(my_generator(), dtype=int)

print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [64]:
a = linspace(0, 1, 10)
print(a)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [65]:
a = random.random(10)
print(np.sort(a))

[0.1597548  0.18892188 0.31722944 0.40370842 0.43879785 0.53621297
 0.62638585 0.82299621 0.95505419 0.98830462]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [67]:
x = np.arange(10)
print(np.add.reduce(x))

45


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [69]:
a = np.random.randint(0, 2, 5)
b = np.random.randint(0, 2, 5)

x = np.allclose(a, b)
y = np.allclose(a, a)
print(a)
print(b)
print(x)
print(y)

[0 0 0 1 0]
[0 0 0 1 1]
False
True


#### 43. Make an array immutable (read-only) (★★☆)

In [70]:
a = np.array([1, 2, 3, 4, 5])
a.flags.writeable = False
a[0] = 10

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [71]:
a = np.random.random((10, 2))
x, y = a[:, 0], a[:, 1]
radius = np.sqrt(x**2 + y**2)
angle = np.arctan2(y, x)
polar = np.column_stack((radius, angle))
print(polar)

[[0.68496461 0.22343151]
 [0.6644998  0.90957845]
 [0.81209475 1.1134061 ]
 [0.40615394 1.56916186]
 [0.82346097 0.04666445]
 [0.60446728 0.69361075]
 [0.84220401 0.41724171]
 [0.83646793 0.76210826]
 [0.97208075 0.84874441]
 [0.43897592 1.27891452]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [72]:
x = np.random.random(10)
x[x.argmax()] = 0
print(x)

[0.73740511 0.6306302  0.83940937 0.71853328 0.7160074  0.68157879
 0.57666925 0.47228927 0.         0.52294583]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [73]:
x = np.linspace(0, 1, 5)
y = np.linspace(0, 1, 5)
X, Y = np.meshgrid(x, y)
coords = np.column_stack((X.ravel(), Y.ravel()))
print(coords)

[[0.   0.  ]
 [0.25 0.  ]
 [0.5  0.  ]
 [0.75 0.  ]
 [1.   0.  ]
 [0.   0.25]
 [0.25 0.25]
 [0.5  0.25]
 [0.75 0.25]
 [1.   0.25]
 [0.   0.5 ]
 [0.25 0.5 ]
 [0.5  0.5 ]
 [0.75 0.5 ]
 [1.   0.5 ]
 [0.   0.75]
 [0.25 0.75]
 [0.5  0.75]
 [0.75 0.75]
 [1.   0.75]
 [0.   1.  ]
 [0.25 1.  ]
 [0.5  1.  ]
 [0.75 1.  ]
 [1.   1.  ]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [75]:
x = np.arange(4)
z = x + 0.5
y = 1.0 / np.subtract.outer(x, z)
print(y)

[[-2.         -0.66666667 -0.4        -0.28571429]
 [ 2.         -2.         -0.66666667 -0.4       ]
 [ 0.66666667  2.         -2.         -0.66666667]
 [ 0.4         0.66666667  2.         -2.        ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [76]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [82]:
a = np.array(np.random.random((5, 3)))
print(a)

[[0.19711123 0.33102197 0.93624803]
 [0.31339504 0.35606383 0.70452706]
 [0.98941322 0.06950379 0.50385705]
 [0.519994   0.34752753 0.38627779]
 [0.84246862 0.87452726 0.53348738]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [83]:
x = np.arange(100)
y = np.random.randint(0, 100)
i = (np.abs(x - y)).argmin()
print(x[i])

65


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [84]:
vector = np.zeros(10, [ ('position', [ ('x', float),
                                       ('y', float)]),
                       
                        ('color',    [ ('r', float),
                                       ('g', float),
                                       ('b', float)])])
print(vector)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [88]:
vector = np.random.random((100,2))
X,Y = np.atleast_2d(vector[:,0], vector[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.23788925 0.81188255 ... 0.25158533 0.77229835 0.71810773]
 [0.23788925 0.         1.03174973 ... 0.38200512 0.99904679 0.87729807]
 [0.81188255 1.03174973 0.         ... 0.68614614 0.08393905 0.39682221]
 ...
 [0.25158533 0.38200512 0.68614614 ... 0.         0.67081041 0.49567292]
 [0.77229835 0.99904679 0.08393905 ... 0.67081041 0.         0.44631466]
 [0.71810773 0.87729807 0.39682221 ... 0.49567292 0.44631466 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [86]:
a = (np.random.rand(10)*5).astype(np.float32)
int_a = a.view(np.int32)
print(int_a)

[1017359353 1076638572 1065894361 1082458537 1065178843 1082660497
 1079367076 1077817946 1075308903 1032883919]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
data = np.genfromtxt('file.csv', delimiter=',', filling_values=np.nan)

print(data)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [89]:
matrix = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(matrix):
    print(index, value)
for index in np.ndindex(matrix.shape):
    print(index, matrix[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [90]:
x, y = np.meshgrid(np.linspace(-1, 1, 5), np.linspace(-1, 1, 5))
z = np.sqrt(x * x + y * y)
Gauss = np.exp(-(z**2))
print(Gauss)

[[0.13533528 0.2865048  0.36787944 0.2865048  0.13533528]
 [0.2865048  0.60653066 0.77880078 0.60653066 0.2865048 ]
 [0.36787944 0.77880078 1.         0.77880078 0.36787944]
 [0.2865048  0.60653066 0.77880078 0.60653066 0.2865048 ]
 [0.13533528 0.2865048  0.36787944 0.2865048  0.13533528]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [91]:
arr = np.zeros((5, 5))
p = 5
indices = np.random.randint(0, arr.size, p)
arr.flat[indices] = 1
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [92]:
x = np.random.rand(5, 5)
check = x - x.mean(axis=1).reshape(-1, 1)
print(check)

[[ 0.10232743 -0.29727576  0.38714518 -0.21165233  0.01945548]
 [-0.36479935  0.13959336  0.01581493  0.24124874 -0.03185768]
 [ 0.11764031 -0.22737257  0.38643632 -0.05798225 -0.21872181]
 [ 0.06795579 -0.28360245 -0.20099816  0.3525318   0.06411302]
 [ 0.13878642 -0.2083964  -0.18262099  0.27225159 -0.02002062]]


#### 59. How to sort an array by the nth column? (★★☆)

In [93]:
x = np.random.randint(0, 10, (3, 3))
print(x)
print(x[x[:, 0].argsort()])

[[4 4 9]
 [2 9 6]
 [4 1 8]]
[[2 9 6]
 [4 4 9]
 [4 1 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [94]:
x = np.random.randint(0, 3, (3, 10))
print((~x.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [95]:
x = np.random.uniform(0, 1, 10)
y = x.flat[np.abs(x - 0.5).argmin()]
print(y)

0.4585513623267746


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [96]:
a = np.random.random((1, 3))
b = np.random.random((3, 1))
it = np.nditer([a, b], flags=['external_loop'], op_flags=[['readonly'], ['readonly']])
sum = 0
for a, b in it:
    sum += a + b
print(sum)

[2.94754342 2.08716138 2.16126844]


#### 63. Create an array class that has a name attribute (★★☆)

In [97]:
class MyArray(np.ndarray):
    def __new__(cls, array, name="no_name"):
        x = np.asarray(array).view(cls)
        x.name = name
        return x
    def __final__(m, x):
        if x is None:
            return
        m.info = getattr(x, 'name', "no_name")

example = MyArray(np.arange(3), "example_3")
print(example.name)

example_3


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [99]:
x = np.ones((10), dtype=int)
a = np.random.randint(0, 10, 10)
np.add.at(x, a, 1)
print(a)
print(x)

[4 6 1 1 6 5 0 4 1 6]
[2 4 1 1 3 2 4 1 1 1]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [100]:
x = [1, 2, 3, 4, 5, 6]
f = [1, 3, 9, 3, 4, 1]
check = np.bincount(f, x)
print(check)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [101]:
w, h = 16, 16
x = np.random.randint(0, 2, (h, w, 3)).astype(np.ubyte)
print(np.unique(x))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [102]:
x = np.random.randint(0, 10, (3, 4, 3, 4))
sum = x.sum(axis=(-2, -1))
print(sum)

[[47 49 64 51]
 [55 61 64 72]
 [64 39 44 78]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [103]:
d = np.random.randint(0, 5, 100)
s = np.random.randint(0, 10, 100)
sum = np.bincount(s, weights=d)
count = np.bincount(s)
mean = sum / count
print(mean)

[2.5        2.11111111 2.25       2.8        1.88888889 1.92857143
 1.66666667 2.14285714 1.55555556 1.5       ]


#### 69. How to get the diagonal of a dot product? (★★★)

In [104]:
x = np.random.uniform(0, 1, (5, 5))
y = np.random.uniform(0, 1, (5, 5))
check = np.diag(np.dot(x, y))
print(check)

[0.64548654 0.57107747 0.94855054 1.21160034 1.23536268]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [105]:
x = np.array([1, 2, 3, 4, 5])
n_zeros = 3
y = np.zeros(len(x) + (len(x) - 1) * n_zeros)
y[::n_zeros + 1] = x

print(y)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [106]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [107]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

arr[[1, 2]] = arr[[2, 1]]
print(arr)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [108]:
triplets = np.random.randint(0, 10, size=(10, 3))
segments = set()

for triplet in triplets:
    for i in range(3):
        j = (i + 1) % 3
        segment = tuple(sorted((triplet[i], triplet[j])))
        segments.add(segment)

print(list(segments))

[(4, 9), (4, 6), (5, 7), (8, 9), (0, 5), (0, 8), (2, 5), (6, 8), (4, 5), (5, 6), (4, 8), (3, 6), (5, 9), (2, 4), (1, 5), (7, 9), (4, 7), (0, 9), (2, 3), (2, 9), (1, 7), (2, 6), (7, 8)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [109]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [110]:
def moving_average(a, n) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

vector = np.arange(20)
print(moving_average(vector, n=4))

[ 1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5 11.5 12.5 13.5 14.5
 15.5 16.5 17.5]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [111]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
vector = rolling(np.arange(10), 3)
print(vector)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [112]:
vector = np.random.uniform(-1.0,1.0,10)
print(vector)
print()
print(np.negative(vector, out=vector))

[ 0.89421152 -0.9501094   0.84254263  0.49090704 -0.21653612 -0.47384106
 -0.60788346  0.28288003 -0.14785169  0.29944261]

[-0.89421152  0.9501094  -0.84254263 -0.49090704  0.21653612  0.47384106
  0.60788346 -0.28288003  0.14785169 -0.29944261]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [113]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 4.98601051  0.15078694 15.27296801 17.15805046  3.38567241  9.81863848
  8.18470034 15.36169028  9.79149321 15.96756072]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [115]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 1.29309279  3.14969746  5.1739054   8.15862118  2.51577956  3.48985754
   7.27522564  7.07709839  8.56040047  3.49892337]
 [ 5.86839079  0.85275015  5.72083659  1.79533862  0.14047767  2.65007363
   3.49542614  0.90536729  0.87211837  5.10828975]
 [16.43630443 11.4195607   9.38400054  9.5801577  10.2477955   7.35468189
   7.06184701  2.65961568  9.36212177  2.43496108]
 [ 6.02466548  1.25335229  1.80111396  0.90004779  0.91910904  1.0115338
   3.00168013  3.21391975  1.45990569  0.90028275]
 [ 4.00989553  9.02356189  2.28137937  5.49231737  9.84734921 11.99619795
  13.36246308  4.22201412  7.0733416   7.59107536]
 [ 1.91411188  7.21106166  7.61147311  0.69258174  8.83672743 11.73890299
  11.65992193  8.22601601  2.54262027 11.88996062]
 [12.38285327  7.89889402  0.67912596  0.47083672  8.23711685  6.76485038
   3.74808202 10.15221807  0.75127075  5.62167151]
 [ 1.64356913  3.07854466  0.51022743  4.68801246  3.20679041  4.86181807
   7.31101457  2.54720546  5.46981178  1.17701933]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [117]:
vector = np.arange(1,15,dtype=np.uint32)
stridedMatrix = stride_tricks.as_strided(vector,(11,4),(4,4))
print(stridedMatrix)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [118]:
a = np.random.uniform(0,1,(10,10))
rank = np.linalg.matrix_rank(a)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [119]:
a = np.random.randint(0, 10, 20)
a = np.bincount(a).argmax()
print(a)

2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [125]:
matrix = np.random.randint(0, 10, size=(10, 10))
block_size = 3

output_shape = (matrix.shape[0] - block_size + 1, matrix.shape[1] - block_size + 1, block_size, block_size)
strides = matrix.strides + matrix.strides
blocks = np.lib.stride_tricks.as_strided(matrix, shape=output_shape, strides=strides)

print(blocks)


[[[[8 6 7]
   [0 7 5]
   [0 6 2]]

  [[6 7 5]
   [7 5 2]
   [6 2 1]]

  [[7 5 2]
   [5 2 3]
   [2 1 5]]

  [[5 2 0]
   [2 3 7]
   [1 5 7]]

  [[2 0 7]
   [3 7 2]
   [5 7 2]]

  [[0 7 6]
   [7 2 4]
   [7 2 0]]

  [[7 6 0]
   [2 4 3]
   [2 0 8]]

  [[6 0 4]
   [4 3 1]
   [0 8 3]]]


 [[[0 7 5]
   [0 6 2]
   [3 2 7]]

  [[7 5 2]
   [6 2 1]
   [2 7 2]]

  [[5 2 3]
   [2 1 5]
   [7 2 4]]

  [[2 3 7]
   [1 5 7]
   [2 4 1]]

  [[3 7 2]
   [5 7 2]
   [4 1 6]]

  [[7 2 4]
   [7 2 0]
   [1 6 6]]

  [[2 4 3]
   [2 0 8]
   [6 6 0]]

  [[4 3 1]
   [0 8 3]
   [6 0 0]]]


 [[[0 6 2]
   [3 2 7]
   [9 8 8]]

  [[6 2 1]
   [2 7 2]
   [8 8 5]]

  [[2 1 5]
   [7 2 4]
   [8 5 1]]

  [[1 5 7]
   [2 4 1]
   [5 1 8]]

  [[5 7 2]
   [4 1 6]
   [1 8 4]]

  [[7 2 0]
   [1 6 6]
   [8 4 2]]

  [[2 0 8]
   [6 6 0]
   [4 2 9]]

  [[0 8 3]
   [6 0 0]
   [2 9 3]]]


 [[[3 2 7]
   [9 8 8]
   [3 5 8]]

  [[2 7 2]
   [8 8 5]
   [5 8 0]]

  [[7 2 4]
   [8 5 1]
   [8 0 7]]

  [[2 4 1]
   [5 1 8]
   [0 7 4]]

  [[4 1 6]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [127]:
class Sym(np.ndarray):
    def __set__(m, i, v):
        a, b = i
        super(Sym, m).__set__((a, b), v)
        super(Sym, m).__set__((b, a), v)

def switch(x):
    return np.asarray(x + x.T - np.diag(x.diagonal())).view(Sym)

a = switch(np.random.randint(0, 5, (5, 5)))
a[2, 3] = 12
print(a)

[[ 0  4  5  3  2]
 [ 4  4  4  4  0]
 [ 5  4  4 12  5]
 [ 3  4  1  2  5]
 [ 2  0  5  5  2]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [129]:
n, p = 12, 10
z = np.ones((p, n, n), dtype=int)
y = np.ones((p, n, 1), dtype=int)
x = np.tensordot(z, y, axes=[[0, 2], [0, 1]])
print(x)

[[120]
 [120]
 [120]
 [120]
 [120]
 [120]
 [120]
 [120]
 [120]
 [120]
 [120]
 [120]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [130]:
x = np.ones((16, 16), dtype=int)
check = np.add.reduceat(np.add.reduceat(x, np.arange(0, x.shape[0], 4), axis=0),
                                        np.arange(0, x.shape[1], 4), axis=1)
print(check)

[[16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [133]:
def iterate(Z):
    N = (Z[0:-2, 0:-2] + Z[0:-2, 1:-1] + Z[0:-2, 2:] +
         Z[1:-1, 0:-2] + Z[1:-1, 2:] + Z[2:, 0:-2] + 
         Z[2:, 1:-1] + Z[2:, 2:])

    birth = (N == 3) & (Z[1:-1, 1:-1] == 0)
    survive = ((N == 2) | (N == 3)) & (Z[1:-1, 1:-1] == 1)
    Z[...] = 0
    Z[1:-1, 1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0, 2, (50, 50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [134]:
a = np.arange(1000)
np.random.shuffle(a)
n = 3

print (a[np.argsort(a)[-n:]])

[997 998 999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [136]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8])
grid = np.meshgrid(v1, v2, v3, indexing='ij')
cartesian_product = np.stack(grid, axis=-1).reshape(-1, len(grid))

print(cartesian_product)

[[1 4 7]
 [1 4 8]
 [1 5 7]
 [1 5 8]
 [1 6 7]
 [1 6 8]
 [2 4 7]
 [2 4 8]
 [2 5 7]
 [2 5 8]
 [2 6 7]
 [2 6 8]
 [3 4 7]
 [3 4 8]
 [3 5 7]
 [3 5 8]
 [3 6 7]
 [3 6 8]]


#### 91. How to create a record array from a regular array? (★★★)

In [139]:
a = np.array([1, 2, 3])
b = np.array(['first', 'second', 'third'])
c = np.array([0.1, 0.2, 0.3])

rec = np.rec.fromarrays([a, b, c], names='field1,field2,field3')

print(rec)
print(rec.field2)

[(1, 'first', 0.1) (2, 'second', 0.2) (3, 'third', 0.3)]
['first' 'second' 'third']


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [142]:
x = np.random.rand(int(5e5))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

32.9 ms ± 2.78 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
7.56 ms ± 293 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
5.12 ms ± 173 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [143]:
A = np.random.randint(0, 5, (8, 3))
B = np.random.randint(0, 5, (2, 2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3, 1)).all(1))[0]
print(rows)

[2 3 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [145]:
A = np.array([[1, 2, 3],
              [2, 2, 3],
              [4, 5, 6],
              [7, 7, 7],
              [8, 9, 9],
              [8, 8, 8],
              [2, 2, 2],
              [3, 3, 3],
              [1, 1, 1],
              [4, 4, 4]])

unique_rows = np.unique(A, axis=1)
unequal_rows = A[np.where(np.apply_along_axis(len, 1, unique_rows) != 1)]

print(unique_rows)

[[1 2 3]
 [2 2 3]
 [4 5 6]
 [7 7 7]
 [8 9 9]
 [8 8 8]
 [2 2 2]
 [3 3 3]
 [1 1 1]
 [4 4 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [146]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [148]:
array = np.random.randint(0, 2, (6, 3))
u_array = np.unique(array, axis=0)
print(u_array)

[[0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [149]:
A = np.random.uniform(0, 1, 5)
B = np.random.uniform(0, 1, 5)

np.einsum('i->', A)
np.einsum('i,i->i', A, B)
np.einsum('i,i', A, B)
np.einsum('i,j->ij', A, B)

array([[0.31566981, 0.06551968, 0.17739994, 0.09617942, 0.44260589],
       [0.06600242, 0.01369931, 0.037092  , 0.02010985, 0.09254308],
       [0.14252784, 0.02958274, 0.08009771, 0.0434259 , 0.19984066],
       [0.48939322, 0.1015773 , 0.27502892, 0.1491101 , 0.68618639],
       [0.19060605, 0.03956174, 0.10711668, 0.05807454, 0.26725192]])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [158]:
X = np.random.rand(100)
Y = np.random.rand(100)

path_length = np.cumsum(np.sqrt(np.diff(X)**2 + np.diff(Y)**2))
path_length = np.insert(path_length, 0, 0)

num_samples = 20

samples = np.linspace(0, path_length[-1], num_samples)

x_samples = np.interp(samples, path_length, X)
y_samples = np.interp(samples, path_length, Y)

print(np.column_stack((x_samples, y_samples)))

[[0.12357634 0.78342952]
 [0.16046495 0.72934177]
 [0.41790631 0.86481353]
 [0.21914183 0.37018656]
 [0.27515534 0.50444949]
 [0.65935751 0.67540055]
 [0.61470911 0.47504888]
 [0.49499825 0.15990279]
 [0.23794708 0.12746829]
 [0.78143486 0.50782699]
 [0.44589169 0.82889851]
 [0.43088626 0.66450101]
 [0.63251358 0.50900134]
 [0.90674021 0.29116084]
 [0.66135632 0.4484265 ]
 [0.27842991 0.39469035]
 [0.29578639 0.20373992]
 [0.61460584 0.68193654]
 [0.19791302 0.78376567]
 [0.61138362 0.08874863]]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [159]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [160]:
X = np.random.randn(100)
N = 1000
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.22992815  0.20577883]
